package com.aaronicsubstances.cs_and_math.parsing.pratt;

import com.aaronicsubstances.cs_and_math.parsing.GenericToken;

/**
 * A simple token class. These are generated by Lexer and consumed by Parser.
 */
public final class DefaultToken extends GenericToken {
    private final TokenType enumType;

    public DefaultToken(TokenType type, String text) {
        super(type.ordinal(), text);
        this.enumType = type;
    }

    @Override
    public String toString() { 
        return text;
    }

    public TokenType getEnumType() {
        return enumType;
    }
}
